[agent]
name = "interface"
version = "0.0.1"

[options.OPENAI_API_KEY]
type = "string"
description = "OpenAI API Key"

[runtimes.executable]
command = ["bash", "examples/camel-search-maths/venv.sh", "examples/camel-search-maths/mcp_example_camel_interface.py"]

[export.executable]
quantity = 30
pricing = { min_price = 1.0, max_price = 1000.0 }