applications:
  - id: "app"
    name: "Default Application"
    description: "Default application for testing"
    privacyKeys:
      - "default-key"
      - "public"
      - "priv"

# Registry of agents we can orchestrate
registry:
  repounderstanding:
    # Exposed configuration for consumers of this agent
    options:
      - name: "OPENAI_API_KEY"
        type: "string"
        description: "OpenAI API Key"
      - name: "GITHUB_ACCESS_TOKEN"
        type: "string"
        description: "GitHub Access Token"

    # How this agent is actually orchestrated locally
    runtime:
      type: "docker"
      environment:
        - name: "API_KEY"
          from: "OPENAI_API_KEY"
        - name: "GITHUB_ACCESS_TOKEN"
          from: "GITHUB_ACCESS_TOKEN"
      image: "coralprotocol/coral-repounderstanding:latest"

  deepresearch:
    options:
      - name: "OPENAI_API_KEY"
        type: "string"
        description: "OpenAI API Key"
      - name: "LINKUP_API_KEY"
        type: "string"
        description: "LinkUp API Key. Get from https://linkup.so/"

    runtime:
      type: "docker"
      environment:
        - name: "API_KEY"
          from: "OPENAI_API_KEY"
      image: "coralprotocol/coral-opendeepresearch:latest"

  interface:
    options:
      - name: "OPENAI_API_KEY"
        type: "string"
        description: "OpenAI API Key"
      - name: "HUMAN_RESPONSE"
        type: "string"
        description: "Human response to be used in the interface agent"

    runtime:
      type: "docker"
      image: "coralprotocol/coral-interface-agent:latest"
      environment:
        - name: "API_KEY"
          from: "OPENAI_API_KEY"
        - name: "HUMAN_RESPONSE"
          from: "HUMAN_RESPONSE"

  interface-local:
    options:
      - name: "OPENAI_API_KEY"
        type: "string"
        description: "OpenAI API Key"
      - name: "HUMAN_RESPONSE"
        type: "string"
        description: "Human response to be used in the interface agent"

    runtime:
      type: "executable"
      command:
        [
          "bash",
          "-c",
          "cd ../Coral-Interface-Agent && /home/suman/.local/bin/uv sync && /home/suman/.local/bin/uv run 0-langchain-interface.py",
        ]
      environment:
        - name: "API_KEY"
          from: "OPENAI_API_KEY"
        - name: "HUMAN_RESPONSE"
          from: "HUMAN_RESPONSE"