applications:
  - id: "app"
    name: "Default Application"
    description: "Default application for testing"
    privacyKeys:
      - "default-key"
      - "public"
      - "priv"
registry:
  langchain-pandas:
    options:
      - name: "API_KEY"
        type: "string"
        description: "API key for the service"
    runtime:
      type: "executable"
      command: ["powershell","-ExecutionPolicy", "Bypass", "-File", "${PROJECT_DIR}/run_agent.ps1","langchain-pandas-agent.py"]
      environment:
        - name: "API_KEY"
          from: "API_KEY"
        - name: "MODEL"
          value: "gpt-4.1"
        - name: "LLM_MODEL_PROVIDER"
          value: "openai"
