const path = require('path');
const fs = require('fs');
const { CONFIG_PROFILES_DIR, pkg, LLM_PROVIDERS } = require('./constants');

function getProfileDir(profileName) {
  return path.join(CONFIG_PROFILES_DIR, profileName);
}

function getConfigProfilePath(profileName) {
  return path.join(getProfileDir(profileName), `${profileName}-coral-server-config.toml`);
}

function ensureConfigProfileDir(profileName) {
  const profileDir = getProfileDir(profileName);
  if (!fs.existsSync(profileDir)) {
    fs.mkdirSync(profileDir, { recursive: true });
  }
}

function configProfileExists(profileName) {
  return fs.existsSync(getConfigProfilePath(profileName));
}

function generateDefaultConfig() {
  const templatePath = path.join(__dirname, '..', 'default-dev-config.toml');
  if (!fs.existsSync(templatePath)) {
    // Fallback if template missing
    return `# Coral Server Configuration Profile\n# Template not found at ${templatePath}\n`;
  }
  
  let content = fs.readFileSync(templatePath, 'utf8');

  // Remove the "reference" message (line 10 in original)
  content = content.replace(/^# This file is a reference.*?\n/m, '');
  // Also remove the next few lines that are part of that note if they exist
  content = content.replace(/^# NOTE: Agent-specific configuration lives in each agent's own.*?\n/m, '');
  content = content.replace(/^#       coral-agent.toml\..*?\n/m, '');

  const header = `# Coral Server Configuration Profile
# Generated by coralos-dev v${pkg.version}
# Documentation: https://docs.coralos.ai/

`;
  return header + content;
}

function buildConfigFromWizardResults(providers, authKey, coralApiKey) {
  let config = generateDefaultConfig();

  if (coralApiKey) {
    const cloudRegex = /\[cloud\]\napiKey = ""/m;
    if (cloudRegex.test(config)) {
      config = config.replace(cloudRegex, `[cloud]\napiKey = "${coralApiKey}"`);
    }
  }

  if (authKey) {
    const authRegex = /# \[auth\]\n# keys = \["some-secure-password"\]/m;
    if (authRegex.test(config)) {
      config = config.replace(authRegex, `[auth]\nkeys = ["${authKey}"]`);
    } else {
      config += `\n[auth]\nkeys = ["${authKey}"]\n`;
    }
  }

  config += '\n# --- Configured LLM Providers ---\n';
  for (const p of providers) {
    const providerInfo = LLM_PROVIDERS.find(lp => lp.id === p.id);
    const name = providerInfo ? providerInfo.name : p.id;
    let format = 'OpenAI';
    let baseUrl = '';

    if (p.id === 'openai') {
      format = 'OpenAI';
      baseUrl = 'https://api.openai.com';
    } else if (p.id === 'anthropic') {
      format = 'Anthropic';
      baseUrl = 'https://api.anthropic.com';
    } else if (p.id === 'openrouter') {
      format = 'OpenAI';
      baseUrl = 'https://openrouter.ai/api/v1';
    }

    if (p.working) {
      config += `[[llm-proxy.providers]]\nname = "${name}"\nformat = "${format}"\napiKey = "${p.apiKey}"\nbaseUrl = "${baseUrl}"\n\n`;
    } else if (p.apiKey) {
      config += `# [[llm-proxy.providers]]\n# name = "${name}"\n# format = "${format}"\n# apiKey = "${p.apiKey}"\n# baseUrl = "${baseUrl}"\n\n`;
    }
  }

  return config;
}

module.exports = {
  getProfileDir,
  getConfigProfilePath,
  ensureConfigProfileDir,
  configProfileExists,
  generateDefaultConfig,
  buildConfigFromWizardResults,
};
