const path = require('path');
const fs = require('fs');
const { CONFIG_PROFILES_DIR, pkg } = require('./constants');

function getProfileDir(profileName) {
  return path.join(CONFIG_PROFILES_DIR, profileName);
}

function getConfigProfilePath(profileName) {
  return path.join(getProfileDir(profileName), `${profileName}-coral-server-config.toml`);
}

function ensureConfigProfileDir(profileName) {
  const profileDir = getProfileDir(profileName);
  if (!fs.existsSync(profileDir)) {
    fs.mkdirSync(profileDir, { recursive: true });
  }
}

function configProfileExists(profileName) {
  return fs.existsSync(getConfigProfilePath(profileName));
}

function generateDefaultConfig() {
  const templatePath = path.join(__dirname, '..', '..', 'default-dev-config.toml');
  if (!fs.existsSync(templatePath)) {
    // Fallback if template missing
    return `# Coral Server Configuration Profile\n# Template not found at ${templatePath}\n`;
  }
  
  let content = fs.readFileSync(templatePath, 'utf8');

  // Remove the "reference" message (line 10 in original)
  content = content.replace(/^# This file is a reference.*?\n/m, '');
  // Also remove the next few lines that are part of that note if they exist
  content = content.replace(/^# NOTE: Agent-specific configuration lives in each agent's own.*?\n/m, '');
  content = content.replace(/^#       coral-agent.toml\..*?\n/m, '');

  const header = `# Coral Server Configuration Profile
# Generated by coralos-dev v${pkg.version}
# Documentation: https://docs.coralos.ai/

`;
  return header + content;
}

function buildConfigFromWizardResults(providers, authKey) {
  let config = generateDefaultConfig();

  // Add auth keys if provided
  if (authKey) {
    const authRegex = /# \[auth\]\n# keys = \["some-secure-password"\]/m;
    if (authRegex.test(config)) {
      config = config.replace(authRegex, `[auth]\nkeys = ["${authKey}"]`);
    } else {
      config += `\n[auth]\nkeys = ["${authKey}"]\n`;
    }
  }

  // Add providers
  config += '\n# --- Configured LLM Providers ---\n';
  config += '[llm-proxy.providers]\n';
  for (const p of providers) {
    if (p.working) {
      config += `[llm-proxy.providers.${p.id}]\napiKey = "${p.apiKey}"\n\n`;
    } else if (p.apiKey) {
      config += `# [llm-proxy.providers.${p.id}]\n# apiKey = "${p.apiKey}"\n\n`;
    }
  }

  return config;
}

module.exports = {
  getProfileDir,
  getConfigProfilePath,
  ensureConfigProfileDir,
  configProfileExists,
  generateDefaultConfig,
  buildConfigFromWizardResults,
};
